//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceDetRec.WPFClient.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public byte[] Data { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public int PersonId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
